language: node_js
node_js:
    - '10'
before_install:
    - if [[ `npm -v` != 5* ]]; then npm i -g npm@latest; fi
after_success:
    - make build
deploy:
    provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $ACCESS_KEY
    bucket: scottdoxey.com
    skip_cleanup: true
    acl: public_read
    on:
        branch: master
