language: node_js
node_js:
    - '12'
after_success:
    - node --version
    - npm --version
    - make build
deploy:
    provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: scottdoxey.com
    skip_cleanup: true
    acl: public_read
    on:
        branch: master
